export const FORECAST_RESIZE_DATA = 'FORECAST_RESIZE_DATA';
export const FORECAST_UPDATE_DATA = 'FORECAST_UPDATE_DATA';
export const FORECAST_CLEAR_DATA = 'FORECAST_CLEAR_DATA';

export const FORECAST_CALCULATE = 'FORECAST_CALCULATE';
export const FORECAST_EXPORT = 'FORECAST_EXPORT';
