export const CA_RESIZE_DATA = 'CA_RESIZE_DATA';
export const CA_UPDATE_DATA = 'CA_UPDATE_DATA';
export const CA_UPDATE_LABEL_POSITION = 'CA_UPDATE_LABEL_POSITION';
export const CA_UPDATE_SELECTED_POINT = 'CA_UPDATE_SELECTED_POINT';
export const CA_CLEAR_DATA = 'CA_CLEAR_DATA';

export const CA_CALCULATE = 'CA_CALCULATE';
